#!/bin/bash

while true; do
read -rsn1 input

#
# if "R" is pressed, play a remote video with mpv
#
if [ "$input" = "R" ]; then
  mpv -vo caca https://www.youtube.com/watch?v=EV3TdFuQy1w
fi

#
# if "L" is pressed, play a local video with mpv
#
if [ "$input" = "L" ]; then
  mpv -vo caca bash-mov-test.mp4
fi

#
# if "f" is pressed, play sound with sox
#
if [ "$input" = "f" ]; then
  play shelltest.mp3
fi

#
# if "f" is pressed, terminate
#
if [ "$input" = "s" ]; then
  exit 1
fi

done
